language: swift
osx_image: xcode9.3

install: true

before_install:
 - gem install cocoapods
 - pod --version

script:
 - cd Constrictor
 - xcodebuild -project Constrictor.xcodeproj -scheme Constrictor -destination "platform=iOS Simulator,name=iPhone 8,OS=11.3" CODE_SIGNING_REQUIRED=NO clean test
 - bash <(curl -s https://codecov.io/bash) -cF swift
 - xcodebuild -project Constrictor.xcodeproj -scheme Constrictor -destination "platform=iOS Simulator,name=iPhone 5s,OS=9.0" CODE_SIGNING_REQUIRED=NO clean test
 - bash <(curl -s https://codecov.io/bash) -cF swift
 - cd ..

 - cd Example
 - pod repo update && pod update
 - set -o pipefail
 - xcodebuild -workspace Example.xcworkspace -scheme Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
 - cd ..
 - travis_wait 30 pod lib lint Constrictor.podspec

after_success:
  - bash <(curl -s https://codecov.io/bash)
