language: swift
osx_image: xcode9.3

install: true

env:
  global:
  - PROJECT=Constrictor.xcodeproj
  - FRAMEWORK_SCHEME=Constrictor
  - PODSPEC=Constrictor.podspec
  - PROJECT_EXAMPLE=Example.xcworkspace
  - PROJECT_SCHEME=Example
  - DESTINATION_PLATFORM_LATEST='platform=iOS Simulator,name=iPhone 8,OS=latest'
  - DESTINATION_PLATFORM_OLD='platform=iOS Simulator,name=iPhone 5s,OS=9.0'
  - CODECOV_ENDPOINT=https://codecov.io/bash

before_install:
 - gem install cocoapods
 - pod --version

script:
 - cd Constrictor
 - xcodebuild -project "$PROJECT" -scheme "$FRAMEWORK_SCHEME" -destination "$DESTINATION_PLATFORM_LATEST" CODE_SIGNING_REQUIRED=NO -enableCodeCoverage YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES clean test  | xcpretty -c
 - bash <(curl -s "$CODECOV_ENDPOINT") -cF swift
 - xcodebuild -project "$PROJECT" -scheme "$FRAMEWORK_SCHEME" -destination "$DESTINATION_PLATFORM_OLD" CODE_SIGNING_REQUIRED=NO -enableCodeCoverage YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES clean test  | xcpretty -c
 - bash <(curl -s "$CODECOV_ENDPOINT") -cF swift
 - cd ..

 - cd "$PROJECT_SCHEME"
 - pod repo update && pod update
 - set -o pipefail
 - xcodebuild -workspace "$PROJECT_EXAMPLE" -scheme "$PROJECT_SCHEME" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
 - cd ..
 - travis_wait 30 pod lib lint "$PODSPEC"

after_success:
  - bash <(curl -s "$CODECOV_ENDPOINT")
